#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	bc="bc -ql" \
	cp="cp -iv" \
	dia="dia --integrated" \
	ffmpeg="ffmpeg -hide_banner" \
	mkd="mkdir -pv" \
	mv="mv -iv" \
	rm="rm -vI" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \

# Colorize commands when possible.
alias \
	ls="ls -N --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \

# These common commands are just too long! Abbreviate them.
alias \
	e="$EDITOR" \
	g="git" \
	gaa="git add . && git commit && git push" \
	ka="killall" \
	sdn="shutdown -h now" \
	trem="transmission-remote" \
	v="$EDITOR" \
	xi="sudo xbps-install" \
	xq="xbps-query" \
	xr="sudo xbps-remove -R" \

# XDG Directories Enforcement
alias \
	arduino-cli="arduino-cli --config-file $XDG_CONFIG_HOME/arduino15/arduino-cli.yaml" \
	freecad="freecad -u "$XDG_CONFIG_HOME"/FreeCAD/user.cfg -s "$XDG_CONFIG_HOME"/FreeCAD/system.cfg" \
	nvidia-settings="nvidia-settings --config=${XDG_CONFIG_HOME:-$HOME/.config}/nvidia/nvidia-settings-rc" \
    wget="wget --hsts-file=\"$XDG_CACHE_HOME/wget-hsts\"" \


# Use for statusbar
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	steam="runsteam" \
	hss="hugo server --noHTTPCache" \


