#!/bin/sh
# profile file. Runs on login.
unsetopt PROMPT_SP

set -o allexport
for tmpfile in ~/.config/environment.d/*.conf; do
    # shellcheck disable=SC1090
    . "${tmpfile}"
done
set +o allexport

tmp_dirs="$(find ~/.local/bin -type d -printf %p:)"
PATH="${tmp_dirs%%:}:${PATH}"
unset tmp_dirs
export PATH

# Use nvimpager if it exists
if [ -x "$(command -v nvimpager)" ]; then
    export PAGER='nvimpager'
    export MANPAGER='nvimpager'
    unset MANWIDTH
elif [ -z "${PAGER}" ]; then
    alias myvimpager='nvim -c "set buftype=nofile | AnsiEsc | set so=999"'
    export PAGER='myvimpager'
    export MANPAGER='nvim +Man!'
    export MANWIDTH=999
else
    export MANPAGER="${PAGER}"
    unset MANWIDTH
fi

# Export seperately to make shellcheck happy
LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"                                     # Less set blink time
LESS_TERMCAP_md="$(printf '%b' '[1;36m')"                                     # Less set bold
LESS_TERMCAP_me="$(printf '%b' '[0m')"                                        # Less set sgr0 (no bold, blink, or underline)
LESS_TERMCAP_se="$(printf '%b' '[0m')"                                        # Less set rmso (stop standout)
LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"                                 # Less set smso (standout - reverse video)
LESS_TERMCAP_ue="$(printf '%b' '[0m')"                                        # Less set stop underline
LESS_TERMCAP_us="$(printf '%b' '[1;32m')"                                     # Less set start underline
export LESS_TERMCAP_mb
export LESS_TERMCAP_md
export LESS_TERMCAP_me
export LESS_TERMCAP_se
export LESS_TERMCAP_so
export LESS_TERMCAP_ue
export LESS_TERMCAP_us

# Machine-Specific Configs
if [ -x "$(command -v hostnamectl)" ]; then
    # options: hyprland, dwm
	machine_env="${XDG_CONFIG_HOME}/shell/machines/$(hostnamectl hostname | tr '[:upper:]' '[:lower:]')"
	if [ -r "${machine_env}" ]; then
        # shellcheck disable=SC1090
		. "${machine_env}"
	else
		echo "Could not find config ${machine_env}"
		exit 1
	fi
else
	echo "Could not find hostname"
	exit 1
fi

# Start graphical server on user's current tty if not already running.
if [ "$(tty)" = "/dev/tty1" ]; then
    case ${LAUNCH_DESKTOP_ENV} in
        dwm)
            pidof -s Xorg >/dev/null 2>&1 \
                || exec startx "$XINITRC" ;;
        hyprland)
            export CLUTTER_BACKEND="wayland"
            export GDK_BACKEND="wayland,x11,*"
            export QT_QPA_PLATFORM="wayland;xcb"
            export QT_QPA_PLATFORMTHEME="qt6ct"
            export SDL_VIDEODRIVER="wayland"
            export XDG_CURRENT_DESKTOP="Hyprland"
            export XDG_SESSION_DESKTOP="Hyprland"
            export XDG_SESSION_TYPE="wayland"
            pidof -s Hyprland >/dev/null 2>&1 \
                || exec Hyprland ;;
    esac
fi
