#!/bin/sh

set -o noclobber
set -o noglob
set -o nounset

IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

# ANSI color codes are supported.
# STDIN is disabled, so interactive scripts won't work properly

# Meanings of exit codes:
# code | meaning    | action of ranger
# -----+------------+-------------------------------------------
# 0    | success    | Display stdout as preview
# 1    | no preview | Display no preview at all
# 2    | plain text | Display the plain content of the file

# Script arguments
FILE_PATH="${1}"           # Full path of the highlighted file

# Settings
HIGHLIGHT_SIZE_MAX=262143  # 256KiB
HIGHLIGHT_TABWIDTH=4
HIGHLIGHT_STYLE='pablo'


handle_text() {
	[ "$( stat --printf='%s' -- "${FILE_PATH}" )" -gt "${HIGHLIGHT_SIZE_MAX}" ] && exit 2
	if [ "$( tput colors )" -ge 256 ]; then
		highlight_format='xterm256'
	else
		highlight_format='ansi'
	fi
	highlight --replace-tabs="${HIGHLIGHT_TABWIDTH}" --out-format="${highlight_format}" --style="${HIGHLIGHT_STYLE}" --force -- "${FILE_PATH}"
}

handle_mime() {
	mimetype="${1}"
	case "${mimetype}" in
		application/zip)            atool --list -- "${FILE_PATH}" ;;
		text/html)                  w3m -dump "${FILE_PATH}" ;;
		text/troff)                 man ./ "${FILE_PATH}" | col -b ;;
		text/*|*/xml)               handle_text ;;
		*/pdf)                      pdftotext -l 10 -nopgbrk -q -- "${FILE_PATH}" - ;;
		*opendocument*)             odt2txt "${FILE_PATH}" ;;
		*)                          mediainfo "${FILE_PATH}" || exit 1;;
	esac
}

MIMETYPE="$( file --dereference --brief --mime-type -- "${FILE_PATH}" )"
handle_mime "${MIMETYPE}"
exit 1
