#!/bin/sh
# shellcheck disable=SC2034
LAUNCH_DESKTOP_ENV="hyprland"

QT_AUTO_SCREEN_SCALE_FACTOR=1
XCURSOR_SIZE=48

WLR_DRM_DEVICES="/dev/dri/card1"

PIP_INDEX_URL='https://download.pytorch.org/whl/rocm6.2'
PIP_EXTRA_INDEX_URL='https://pypi.org/simple'
