#!/bin/sh
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export XCURSOR_SIZE=24
export LIBVA_DRIVER_NAME="nvidia"
export GBM_BACKEND="nvidia-drm"
export __GLX_VENDOR_LIBRARY_NAME="nvidia"
export NVD_BACKEND="direct"
export LAUNCH_DESKTOP_ENV="hyprland"
