#!/bin/sh
# shellcheck disable=SC2034

LAUNCH_DESKTOP_ENV="hyprland"

QT_AUTO_SCREEN_SCALE_FACTOR=0.8
GDK_DPI_SCALE=0.8

XCURSOR_SIZE=24

LIBVA_DRIVER_NAME="nvidia"
GBM_BACKEND="nvidia-drm"
__GLX_VENDOR_LIBRARY_NAME="nvidia"
NVD_BACKEND="direct"

PIP_INDEX_URL="https://download.pytorch.org/whl/nightly/cu126"
PIP_EXTRA_INDEX_URL="https://pypi.org/simple"
